export interface EloPlayer {
  id: string
  name: string
  type: 'person' | 'company'
  elo: number
  category: string[]
  linkedProblems: string[]
  bio: string
  peakElo: number
  eloHistory: { date: string; elo: number }[]
}

export const CATEGORIES = [
  'AI',
  'Energy',
  'Space',
  'Biotech',
  'Crypto',
  'Infrastructure',
  'Wealth Creation',
  'Defense',
  'Computing',
  'Health',
] as const

export type PlayerCategory = (typeof CATEGORIES)[number]

export const SEED_PLAYERS: EloPlayer[] = [
  // ═══ AI ═══
  {
    id: 'jensen-huang',
    name: 'Jensen Huang',
    type: 'person',
    elo: 1500,
    category: ['AI', 'Computing'],
    linkedProblems: [],
    bio: 'CEO of NVIDIA. Built the GPU computing platform that powers modern AI.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'nvidia',
    name: 'NVIDIA',
    type: 'company',
    elo: 1500,
    category: ['AI', 'Computing'],
    linkedProblems: [],
    bio: 'The computing platform company powering the AI revolution with GPUs and accelerated computing.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'sam-altman',
    name: 'Sam Altman',
    type: 'person',
    elo: 1500,
    category: ['AI'],
    linkedProblems: [],
    bio: 'CEO of OpenAI. Leading the development of artificial general intelligence.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    type: 'company',
    elo: 1500,
    category: ['AI'],
    linkedProblems: [],
    bio: 'AI research lab building safe and beneficial artificial general intelligence.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'dario-amodei',
    name: 'Dario Amodei',
    type: 'person',
    elo: 1500,
    category: ['AI'],
    linkedProblems: [],
    bio: 'CEO of Anthropic. Building reliable, interpretable, and steerable AI systems.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    type: 'company',
    elo: 1500,
    category: ['AI'],
    linkedProblems: [],
    bio: 'AI safety company building Claude. Focused on making AI systems safe and beneficial.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'demis-hassabis',
    name: 'Demis Hassabis',
    type: 'person',
    elo: 1500,
    category: ['AI', 'Biotech'],
    linkedProblems: [],
    bio: 'CEO of Google DeepMind. Solved protein folding with AlphaFold.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'google-deepmind',
    name: 'Google DeepMind',
    type: 'company',
    elo: 1500,
    category: ['AI', 'Biotech'],
    linkedProblems: [],
    bio: 'AI lab that created AlphaFold, AlphaGo, and Gemini. Pursuing AGI through scientific breakthroughs.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  // ═══ Energy ═══
  {
    id: 'elon-musk',
    name: 'Elon Musk',
    type: 'person',
    elo: 1500,
    category: ['Energy', 'Space', 'AI'],
    linkedProblems: [],
    bio: 'CEO of Tesla and SpaceX. Accelerating the transition to sustainable energy and making humanity multiplanetary.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'tesla',
    name: 'Tesla',
    type: 'company',
    elo: 1500,
    category: ['Energy'],
    linkedProblems: [],
    bio: 'Electric vehicle and clean energy company accelerating the world\'s transition to sustainable energy.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'helion',
    name: 'Helion Energy',
    type: 'company',
    elo: 1500,
    category: ['Energy'],
    linkedProblems: [],
    bio: 'Building the world\'s first fusion power plant. Backed by Sam Altman.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  // ═══ Space ═══
  {
    id: 'spacex',
    name: 'SpaceX',
    type: 'company',
    elo: 1500,
    category: ['Space'],
    linkedProblems: [],
    bio: 'Making humanity multiplanetary with reusable rockets and Starship.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'jeff-bezos',
    name: 'Jeff Bezos',
    type: 'person',
    elo: 1500,
    category: ['Space', 'Wealth Creation', 'Infrastructure'],
    linkedProblems: [],
    bio: 'Founder of Amazon and Blue Origin. Building infrastructure for the next generation of space entrepreneurs.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'blue-origin',
    name: 'Blue Origin',
    type: 'company',
    elo: 1500,
    category: ['Space'],
    linkedProblems: [],
    bio: 'Building a road to space with reusable launch vehicles and orbital infrastructure.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'palmer-luckey',
    name: 'Palmer Luckey',
    type: 'person',
    elo: 1500,
    category: ['Defense'],
    linkedProblems: [],
    bio: 'Founder of Anduril Industries and Oculus VR. Building next-generation defense technology.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'anduril',
    name: 'Anduril Industries',
    type: 'company',
    elo: 1500,
    category: ['Defense'],
    linkedProblems: [],
    bio: 'Defense technology company building autonomous systems and AI-powered military platforms.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  // ═══ Biotech / Health ═══
  {
    id: 'patrick-collison',
    name: 'Patrick Collison',
    type: 'person',
    elo: 1500,
    category: ['Infrastructure', 'Biotech'],
    linkedProblems: [],
    bio: 'CEO of Stripe. Co-founded Fast Grants to accelerate scientific research funding.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'bryan-johnson',
    name: 'Bryan Johnson',
    type: 'person',
    elo: 1500,
    category: ['Health', 'Biotech'],
    linkedProblems: [],
    bio: 'Founder of Blueprint. Measuring and reversing biological aging with rigorous protocols.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'moderna',
    name: 'Moderna',
    type: 'company',
    elo: 1500,
    category: ['Biotech', 'Health'],
    linkedProblems: [],
    bio: 'Pioneering mRNA technology for vaccines and therapeutics against infectious diseases and cancer.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  // ═══ Crypto / Infrastructure ═══
  {
    id: 'balaji-srinivasan',
    name: 'Balaji Srinivasan',
    type: 'person',
    elo: 1500,
    category: ['Crypto', 'Infrastructure'],
    linkedProblems: [],
    bio: 'Former CTO of Coinbase. Author of The Network State. Building decentralized institutions.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'vitalik-buterin',
    name: 'Vitalik Buterin',
    type: 'person',
    elo: 1500,
    category: ['Crypto', 'Infrastructure'],
    linkedProblems: [],
    bio: 'Co-founder of Ethereum. Building programmable money and decentralized governance.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'brian-armstrong',
    name: 'Brian Armstrong',
    type: 'person',
    elo: 1500,
    category: ['Crypto', 'Infrastructure'],
    linkedProblems: [],
    bio: 'CEO of Coinbase. Building an open financial system for the world.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    type: 'company',
    elo: 1500,
    category: ['Crypto', 'Infrastructure'],
    linkedProblems: [],
    bio: 'The most trusted cryptocurrency exchange. Building infrastructure for the cryptoeconomy.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    type: 'company',
    elo: 1500,
    category: ['Infrastructure'],
    linkedProblems: [],
    bio: 'Financial infrastructure for the internet. Increasing the GDP of the internet.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  // ═══ Wealth Creation ═══
  {
    id: 'warren-buffett',
    name: 'Warren Buffett',
    type: 'person',
    elo: 1500,
    category: ['Wealth Creation'],
    linkedProblems: [],
    bio: 'CEO of Berkshire Hathaway. The greatest capital allocator in history.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'charlie-munger',
    name: 'Charlie Munger',
    type: 'person',
    elo: 1500,
    category: ['Wealth Creation'],
    linkedProblems: [],
    bio: 'Vice Chairman of Berkshire Hathaway (legacy). Champion of mental models and rational thinking.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'berkshire-hathaway',
    name: 'Berkshire Hathaway',
    type: 'company',
    elo: 1500,
    category: ['Wealth Creation'],
    linkedProblems: [],
    bio: 'The greatest compounding machine in history. Long-term value creation through rational capital allocation.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'peter-thiel',
    name: 'Peter Thiel',
    type: 'person',
    elo: 1500,
    category: ['Wealth Creation', 'Defense'],
    linkedProblems: [],
    bio: 'Co-founder of PayPal and Palantir. Contrarian investor backing definite optimism.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
  {
    id: 'amazon',
    name: 'Amazon',
    type: 'company',
    elo: 1500,
    category: ['Infrastructure', 'Wealth Creation'],
    linkedProblems: [],
    bio: 'Earth\'s most customer-centric company. Built AWS, the backbone of the modern internet.',
    peakElo: 1500,
    eloHistory: [{ date: '2025-01-01', elo: 1500 }],
  },
]
